DROP TABLE BOLAEXTRAIDA;
DROP TABLE CARTON;
DROP TABLE PARTIDA;
DROP TABLE SALA;
DROP TABLE HISTORIAL;
DROP TABLE USUARIO;

purge recyclebin;


DROP SEQUENCE SEQ_SALA;
DROP SEQUENCE SEQ_PARTIDA;
DROP SEQUENCE SEQ_USUARIO;
DROP SEQUENCE SEQ_CARTON;
DROP SEQUENCE SEQ_HISTORIAL;
DROP SEQUENCE SEQ_BOLAEXTRAIDA;