spring.application.name=BServer

#spring.datasource.url=jdbc:oracle:thin:@localhost:1521/FREEPDB1
spring.datasource.url=jdbc:oracle:thin:@192.168.1.132:1521/FREEPDB1
spring.datasource.username=BHERNANDEZ
spring.datasource.password=BHERNANDEZ
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
#spring.jpa.hibernate.ddl-auto=update
#spring.sql.init.data-locations=classpath:data.sql
#spring.sql.init.mode=always

# Logs SQL (opcional)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

